Update translations
Elfsquad/translations pull request #4
Opened 2023-06-09 15:01 UTC by mirela88

2023-06-12 06:19 UTC, AJJPostma approved these changes

2023-06-12 06:48 UTC, LNLaarhoven requested changes

2023-06-12 06:48 UTC, LNLaarhoven commented on ems_translations.csv
> +State;Provincie;RÃ©gion;Bundesland;Land;Kraj;Land
the encoding on the ems_translations seems wrong. It looks like ANSI encoding and should be UTF-8 encoding. Could you change it to that? If you need help doing that, let me know

2023-06-29 11:52 UTC, LNLaarhoven commented
I will close this PR as it will be combined with the PR that adds Spanish translations

2023-06-29 11:52 UTC, closed without merging